app/models/Role.py
 #coding:utf-8

from .. import db


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(64),unique=True)
    permissions = db.Column(db.Integer)
    users = db.relationship('User',backref='role',lazy='dynamic')

    def __init__(self,name):
        self.name = name

    @staticmethod
    def insert_roles():
        roles = {
            'User': (Permission.WRITE|Permission.COMMENT),
            'Manager': (Permission.WRITE|Permission.COMMENT|Permission.MANAGE),
            'Administrator': (0xff)
        }
        for r in roles:
            role = Role.query.filter_by(name=r).first()
            if role is None:
                role = Role(name=r)
            role.permissions = roles[r]
            db.session.add(role)
        db.session.commit()



class Permission:
    WRITE = 0X01
    COMMENT = 0X02
    MANAGE = 0X04
    ADMINSTER = 0X80


# 定义检查用户权限的自定义修饰器
from functools import wraps
from flask import abort
from flask_login import current_user

def permission_required(permission):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args,**kwargs):
            if not current_user.can(permission):
                abort(403)
            return f(*args,**kwargs)
        return decorated_function
    return decorator()

def admin_required(f):
    return permission_required(Permission.ADMINSTER)(f)

app/models/User.py
# coding:utf-8
# 一个点表示当前目录，每多一个点号则代表向上一层目录。
from .. import db,login_manager
from .Role import Permission
from flask_login import UserMixin,AnonymousUserMixin


class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64))
    password_hash = db.Column(db.String(64))
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))

    def __init__(self,username,password_hash):
        self.username = username
        self.password_hash = password_hash

    def can(self,permissions):
        return self.role is not None and \
               (self.role.permissions&permissions)==permissions

    def is_administrator(self):
        return self.can(Permission.ADMINSTER)


# 定义未定义用户类，为了更方便的对current_user调用can和is_administrator
class AnonymousUser(AnonymousUserMixin):
    def can(self,permissions):
        return False

    def is_administrator(self):
        return False

# 加载用户的回调函数
@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/__init__.py
#coding:utf-8
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'user.login'

def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    login_manager.init_app(app)

    # 附加路由和自定义错误页面
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .user import user as user_blueprint
    app.register_blueprint(user_blueprint)

    return app

app/main/__init__.py
#coding:utf-8
from flask import Blueprint

#参数为蓝本的名字和蓝本所在的模块或包的名字
main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import render_template
from . import main
from app.models.User import User
from app.models.Role import Role
from .. import db


@main.route('/')
def index():
    Role.insert_roles()
    role = Role.query.filter_by(name='User').first()
    user = User.query.filter_by(role=role).all()
    for user1 in user:
        print user1.username
    return render_template('main/index.html')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user',__name__)

from . import views

app/user/views.py
# coding:utf-8
import sys
default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)


from . import user
from flask import request,redirect,render_template,url_for,flash
from app.models.User import User
from flask_login import login_user,login_required,logout_user,current_user


@user.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == "GET":
        return render_template('user/login.html')
    else:
        name = request.form.get("name")
        password = request.form.get("password")
        user = User.query.filter_by(username=name).first()
        if user is not None and user.password_hash == password:
            login_user(user)
            return redirect(request.args.get('next') or url_for('main.index'))
        else:
            flash("用户名或密码错误！")
            return render_template('user/login.html')

# 注销用户
@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash('已注销用户')
    return redirect(request.args.get('next') or url_for('main.index'))

app/templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{{ url_for('static',filename='bootstrap/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='img/icon.jpg') }}" rel="shortcut icon" type="image/x-icon">
    <script src="{{url_for('static',filename='js/jquery-2.1.1.js')}}"></script>
    <script src="{{url_for('static',filename='bootstrap/bootstrap.js')}}"></script>
    <title>博客</title>
</head>
<body>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-12 column">
            <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="row clearfix">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#bs-example-navbar-collapse-1">
                                <!--只在屏幕阅读器中显示-->
                                <span class="sr-only">Toggle navigation</span>
                                <!--汉堡按钮-->
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="{{url_for('main.index')}}">博客</a>
                        </div>

                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="active">
                                    <a href="#">问答</a>
                                </li>
                                <li>
                                    <a href="#">专栏</a>
                                </li>
                                <li>
                                    <a href="#">头条</a>
                                </li>
                            </ul>
                            <div class="col-md-offset-7">
                                <form class="navbar-form navbar-left" role="search">
                                    <div class="form-group">
                                        <input type="text" class="form-control"/>
                                    </div>
                                    <button type="submit" class="btn btn-default">查询</button>
                                </form>
                            </div>
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    {% if current_user.username %}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        {{current_user.username}}
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">个人资料</a></li>
                                        <li><a href="#">设置</a></li>
                                        <li><a href="#">帮助</a></li>
                                        <li class="divider"></li>
                                        <li><a href="{{url_for('user.logout')}}">注销</a></li>
                                    </ul>
                                </li>
                                {% else %}
                                <a href="{{url_for('user.login')}}">登录</a>
                                {% endif %}
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong
                                            class="caret"></strong></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="#">Action</a>
                                        </li>
                                        <li>
                                            <a href="#">Another action</a>
                                        </li>
                                        <li>
                                            <a href="#">Something else here</a>
                                        </li>
                                        <li class="divider">
                                        </li>
                                        <li>
                                            <a href="#">Separated link</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>
</body>
</html>

app/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{{ url_for('static',filename='bootstrap/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static',filename='img/icon.jpg') }}" rel="shortcut icon" type="image/x-icon">
    <script src="{{url_for('static',filename='js/jquery-2.1.1.js')}}"></script>
    <script src="{{url_for('static',filename='bootstrap/bootstrap.js')}}"></script>
    <title>登录</title>
</head>
<body>
<div class="container">
    <div class="row clearfix">
        <div class="col-md-4 column">
        </div>
        <div class="col-md-4 column">
            <form role="form" method="post">
                <div class="form-group">
                    <label>用户名</label>
                    <input type="text" class="form-control" name="name" placeholder="请输入用户名">
                </div>
                <div class="form-group">
                    <label>密码</label>
                    <input type="password" class="form-control" name="password" placeholder="请输入密码">
                </div>
                <div class="form-group">
                    <input type="submit" value="登录" class="form-control">
                </div>
            </form>
            <div class="container">
                {% for message in get_flashed_messages() %}
                <div class="alert alert-warning alert-dismissable" style="width:40%">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 column">
        </div>
    </div>
</div>
</body>
</html>